### ISSUE TITLE
Simplify `a11y-ContrastClosest`

### ISSUE THREAD

**Issue by KittyGiraudel** [at-import/sass-a11y#1]
I was playing with your function and found a way to slightly shorten/simplify your function. I don't know which version you prefer, but I thought I'd leave this here so you can choose:

``` scss
@function a11y-ContrastClosest($color, $background, $alpha: 1) {
  $channels: ();

  @each $channel in "red" "green" "blue" {
    $value: max(0, call($channel, $color) - (call($channel, $background)) / (1 - $alpha));
    $channels: append($channels, min($value, 255));
  }

  @return rgb($channels...);
}
```
